language: python
sudo: false

matrix:
  include:
    - python: "2.7"
      env: DEPS="numpy=1.9* scipy"
    - python: "2.7"
      env: DEPS="numpy=1.9* scipy pillow<3 matplotlib scikit-image jinja2"
    - python: "3.4"
      env: DEPS="numpy=1.9* scipy"
    - python: "3.4"
      env: DEPS="numpy=1.9* scipy pillow<3 matplotlib scikit-image jinja2"

install:
  - conda update --yes conda
  - conda create -n testenv --yes $DEPS nose pip python=$TRAVIS_PYTHON_VERSION
  - conda install -n testenv -c soft-matter --yes pyav tifffile
  - source activate testenv
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then pip install libtiff; fi
  - pip install slicerator jpype1;
  - python setup.py build_ext install


before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; 
    then 
        wget http://repo.continuum.io/miniconda/Miniconda-3.7.3-Linux-x86_64.sh -O miniconda.sh; 
    else 
        wget http://repo.continuum.io/miniconda/Miniconda3-3.7.3-Linux-x86_64.sh -O miniconda.sh; 
    fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH

script: nosetests --nologcapture

